[project]
name = "lindblad-simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.4",
    "qiskit>=2.2.2",
    "quspin>=1.0.0",
    "qutip>=5.2.1",
    "scipy>=1.16.3",
]
